print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/pBrel/DOCUME~1/prCoil/PROJEC~1/Assets/PERSON~1/PASHAB~1/Other/BC_JIG~1.MA"`)
{		
	file -o "C:/Users/pBrel/DOCUME~1/prCoil/PROJEC~1/Assets/PERSON~1/PASHAB~1/Other/BC_JIG~1.MA";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/pBrel/DOCUME~1/prCoil/PROJEC~1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/pBrel/DOCUME~1/prCoil/PROJEC~1/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/pBrel/DOCUME~1/prCoil/PROJEC~1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
